Blog/Areas/Admin/Controllers/PostController.cs
using Blog.Utils;
using DataAccess.Dao;
using DataAccess.Model;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Blog.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin, reader")]
    public class PostController : Controller
    {
        int itemsOnPage = 1;
        int totalPosts;
        // GET: Admin/Post
        public ActionResult Index(int? idUser, int? page, String phrase)
        {
            CategoryDao cd = new CategoryDao();
            ViewBag.Categories = cd.GetAll();

            int pg = page.HasValue ? page.Value : 1;

            UserDao ud = new UserDao();
            User u = ud.GetByLogin(User.Identity.Name);

            PostDao pd = new PostDao();
            if (u.Role.Identificator == "admin")
            {
                IList<Post> articles = pd.getPostsByTitle(phrase, itemsOnPage, (int)pg, out totalPosts);
                ViewBag.Pages = Math.Ceiling((double)totalPosts / (double)itemsOnPage);
                ViewBag.CurrentPage = pg;
                ViewBag.Phrase = phrase;
                if (Request.IsAjaxRequest())
                {
                    return PartialView(articles);
                }
                return View(articles);
            }else
            {
                IList<Post> articles = pd.getByUser((int)u.Id, phrase, itemsOnPage, (int)pg, out totalPosts);
                ViewBag.Pages = Math.Ceiling((double)totalPosts / (double)itemsOnPage);
                ViewBag.CurrentPage = pg;
                if (Request.IsAjaxRequest())
                {
                    return PartialView(articles);
                }
                return View(articles);
            }
        }

        public ActionResult Detail(int? id)
        {
            CategoryDao cd = new CategoryDao();
            ViewBag.Categories = cd.GetAll();
            Post p = new Post();
            if (id != null)
            {
                PostDao pd = new PostDao();
                p = pd.GetById((int)id);
            }
           
            return View(p);
        }


        [HttpPost]
        public ActionResult Save(Post p, HttpPostedFileBase picture, int categoryId, String tag, IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid)
            {

                if (picture != null)
                {
                    if (picture.ContentType == "image/jpeg" || picture.ContentType == "image/png")
                    {
                        System.Drawing.Image image = Image.FromStream(picture.InputStream);
                        Bitmap small = new Bitmap(ImageUtils.ScaleImage(image, 350, 232));
                        Bitmap big = new Bitmap(ImageUtils.ScaleImage(image, 1000, 664));

                        if (p.PreviewImageName != null)
                        {
                            System.IO.File.Delete(Server.MapPath("~/Upload/Small/" + p.PreviewImageName));
                        }
                        if (p.ContentImageName != null)
                        {
                            System.IO.File.Delete(Server.MapPath("~/Upload/" + p.ContentImageName));
                        }

                        p.PreviewImageName = saveImage(small, true);
                        p.ContentImageName = saveImage(big, false);

                        image.Dispose();
                        small.Dispose();
                        big.Dispose();
                    }
                }

                if (!String.IsNullOrEmpty(tag))
                {
                    p.Tags = saveTags(tag);
                }
                p.CreationDate = DateTime.Now;


                CategoryDao cd = new CategoryDao();
                Category c = cd.GetById(categoryId);
                p.Category = c;

                UserDao ud = new UserDao();
                User u = ud.GetByLogin(User.Identity.Name);
                p.Author = u;

               

                PostDao pd = new PostDao();
                if (p.Id != 0)
                {
                    pd.Update(p);
                }
                else
                {
                    pd.Create(p);
                }

                List<BlogImage> results = new List<BlogImage>();
                if (files.Count() != 1)
                {

                    BlogImageDao bid = new BlogImageDao();
                    List<BlogImage> images = bid.findByArticle(p.Id);
                    foreach (BlogImage blogi in images)
                    {
                        System.IO.File.Delete(Server.MapPath("~/Upload/Gallery/" + blogi.Name + blogi.Postfix));
                        System.IO.File.Delete(Server.MapPath("~/Upload/Gallery/Small/" + blogi.Name + "small" + blogi.Postfix));
                        bid.Delete(blogi);
                    }

                    foreach (HttpPostedFileBase hpfb in files)
                    {
                        
                        BlogImage bi = new BlogImage();
                        Guid guid = Guid.NewGuid();
                        bi.Name = guid.ToString();
                        bi.Postfix = ".jpg";
                        bi.Folder = "Gallery";
                        bi.Article = p;
                        bid.Create(bi);
                        results.Add(bi);


                        Bitmap b = new Bitmap(Image.FromStream(hpfb.InputStream));
                        Bitmap bs = new Bitmap(ImageUtils.ScaleImage(b,200,200));
                        b.Save(Server.MapPath("~/Upload/Gallery/" + bi.Name + bi.Postfix), ImageFormat.Jpeg);
                        bs.Save(Server.MapPath("~/Upload/Gallery/Small/" + bi.Name + "small" + bi.Postfix), ImageFormat.Jpeg);
                        b.Dispose();
                        bs.Dispose();
                    }
                }
                


            }
            else
            {
                CategoryDao cd = new CategoryDao();
                ViewBag.Categories = cd.GetAll();
                return View("Detail", p);
            }
            return RedirectToAction("Index");
        }

        private List<Tag> saveTags(String tag)
        {
            string[] tokens = tag.Split(',');

            List<Tag> tags = new List<Tag>();
            TagDao td = new TagDao();

            for(int i = 0; i < tokens.Length; i++)
            {
                    Tag t;
                    t = new Tag();
                    t.Name = tokens[i];

                    td.Create(t);
               
                
                tags.Add(t);
                }
           
            return tags;
        }
 


        private string saveImage(Bitmap b, Boolean small)
        {
            if (small)
            {
                Guid guid = Guid.NewGuid();
                string imageName = guid.ToString() + "_small" + ".jpg";
                b.Save(Server.MapPath("~/Upload/Small/" + imageName), ImageFormat.Jpeg);
                return imageName;
            }
            else
            {
                Guid guid = Guid.NewGuid();
                string imageName = guid.ToString() + ".jpg";
                b.Save(Server.MapPath("~/Upload/" + imageName), ImageFormat.Jpeg);
                return imageName;
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult DeletePost(int Id)
        {
            PostDao pd = new PostDao();
            Post p = pd.GetById(Id);

            System.IO.File.Delete(Server.MapPath("~/Upload/" + p.ContentImageName));
            System.IO.File.Delete(Server.MapPath("~/Upload/Small/" + p.PreviewImageName));

            CommentDao cd = new CommentDao();
            List<Comment> comments = cd.getAllForPost(Id);
            foreach (Comment c in comments)
            {
                cd.Delete(c);
            }

            pd.Delete(p);

            TempData["message-success"] = "Příspěvek " + p.Title + " byl úspěšně vymazán";
            return RedirectToAction("Index");
        }

        public JsonResult SearchTags(string query)
        {
            TagDao td = new TagDao();
            List<String> tags= td.getTagNames(query);
            return Json(tags, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PhotoEdit(int idPost)
        {
            BlogImageDao bid = new BlogImageDao();
            return View();
        }

    }
}

Blog/Areas/Admin/Views/Post/Detail.cshtml
@using DataAccess.Model
@model Post
@{
    ViewBag.Title = "CreatePost";
}

    <h2>Detail příspěvku</h2>

    @using (Html.BeginForm("Save", "Post", FormMethod.Post, new { @class = "form-horizontal" , enctype = "multipart/form-data"}))
    {
        <div class="form-group">
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.Author)
            @Html.HiddenFor(x => x.PreviewImageName)
            @Html.HiddenFor(x => x.ContentImageName)
            <div class="col-sm-10">
                <label>Nadpis</label>
            </div>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Title)
        </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10">
            <label>Kategorie</label>
            </div>
        <div class="col-sm-10">
            @Html.DropDownList("categoryId", new SelectList(ViewBag.Categories, "Id", "Name"), new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Title)      
        </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10">
                <label>Obrázek</label>
            </div>
                <div class="col-sm-10">
                    <input type="file" name="picture" />
                    @if (!String.IsNullOrEmpty(Model.PreviewImageName))
                    {
                        <img src="@Url.Content("~/Upload/Small/" + Model.PreviewImageName)" />
                    }
                </div>
            </div>
        <div class="form-group">
            <div class="col-sm-10">
                <label>Anotace</label>
            </div>
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.Annotation, new { @class = "form-control", @rows = 5 })
                    @Html.ValidationMessageFor(x => x.Annotation)
                </div>
            </div>
        <div class="form-group">
            <div class="col-sm-10">
                <label>Obsah</label>
            </div>
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.Content, new { @class = "form-control formatedText", @rows = 20 })
                    @Html.ValidationMessageFor(x => x.Content)
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-10">
                    <label>Tagy</label>
                </div>
                <div class="col-sm-10">
                   <input type="text" name="tag" class="input-tag" id="tag_input" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-10">
                    <label>Galerie</label>
                </div>
                <div class="col-sm-10">
                    <input type="file" name="files" multiple />
                </div>
            </div>
        <div class="form-group">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary btn-lg btn-block">Uložit</button>
            </div>
        </div>
    }

<script>
$("#tag_input").tagit({

    // Options
    fieldName: "skills",
    availableTags: ["c++", "java", "php", "javascript", "ruby", "python", "c"],
    autocomplete: {
       source: function( request, response ) {
        $.ajax( {
          url: "@Url.Action("SearchTags", "Post")",
          dataType: "json",
          data: {
              query: request.term
          },
          success: function( data ) {
              response(data);
          }
        } );
      },
      minLength: 3,
    } ,

    showAutocompleteOnFocus: false,
    removeConfirmation: false,
    caseSensitive: true,
    allowDuplicates: false,
    allowSpaces: false,
    readOnly: false,
    tagLimit: null,
    singleField: false,
    singleFieldDelimiter: ',',
    singleFieldNode: null,
    tabIndex: null,
    placeholderText: null,

    // Events
    beforeTagAdded: function(event, ui) {
        console.log(ui.tag);
    },
    afterTagAdded: function(event, ui) {
        console.log(ui.tag);
    },
    beforeTagRemoved: function(event, ui) {
        console.log(ui.tag);
    },
    onTagExists: function(event, ui) {
        console.log(ui.tag);
    },
    onTagClicked: function(event, ui) {
        console.log(ui.tag);
    },
    onTagLimitExceeded: function(event, ui) {
        console.log(ui.tag);
    }

});
</script>

Blog/Areas/Admin/Views/Post/Index.cshtml
@using DataAccess.Model
@model List<Post>
@{
    ViewBag.Title = "Index";
}
<h2>Příspěvky</h2>
<div class="panel-body">
    @using (Ajax.BeginForm("Index", "Post", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dynamicContent" }, new { @class = "form-inline" }))
    {
        <div class="form-group">
            <input type="text" size="150" placeholder="Vyhledat článek" name="phrase" class="form-control" />
        </div>
            <input type="submit" value="search" class="btn btn-default" />
     }
</div>

<div class="table-responsive">
    <a href="@Url.Action("Detail", "Post")" class="btn btn-default pull-right">Nový příspěvek</a>
    <table class="table table-striped table-bordered table-responsive">
        <tr>
            <th>Titulek</th>
            <th>Autor</th>
            <th>Datum</th>
            <th>Kategorie</th>
            <th>Tagy</th>
            <th>Akce</th>
        </tr>
        @foreach (Post p in Model)
        {
            <tr>
                <td>@p.Title</td>
                <td>@p.Author.Name @p.Author.Surname</td>
                <td>@p.CreationDate</td>
                <td>@p.Category.Name</td>
                <td>
                    @foreach (Tag t in p.Tags)
                {
                    @t.Name <br/>
                }
                </td>

                <td>
                    <a href="@Url.Action("Detail", "Post", new { id = @p.Id})">Editovat</a>
                    <a href="@Url.Action("DeletePost", "Post", new { id = @p.Id })">Smazat</a>
                    <a href="@Url.Action("Index", "Comment", new { id = @p.Id })">Spravovat komentáře</a>
                </td>
            </tr>
        }
    </table>
</div>
<div class="clearfix"></div>
<ul class="pagination">
    @for (int i = 1; i <= ViewBag.Pages; i++)
    {
    <li>
        @Ajax.ActionLink(@i.ToString(), "Index", new { page = i, phrase = ViewBag.Phrase}, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dynamicContent" })
    </li>
    }

</ul>