Blog/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Model;
using System.Drawing;
using Blog.Utils;
using System.Drawing.Imaging;
using DataAccess.Dao;

namespace Blog.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            CategoryDao cd = new CategoryDao();
            ViewBag.Categories = cd.GetAll();

            PostDao pd = new PostDao();
            return View(pd.GetAll());
        }

        public ActionResult Detail(int? id)
        {
            CategoryDao cd = new CategoryDao();
            ViewBag.Categories = cd.GetAll();
            Post p = new Post();
            if(id != null)
            {
                PostDao pd = new PostDao();
                p = pd.GetById((int)id);
            }
            return View(p);
        }

        [Authorize(Roles = "admin")]
        public ActionResult DetailCategory(int? id)
        {
            CategoryDao cd = new CategoryDao();
            ViewBag.Categories = cd.GetAll();
            Category c = new Category();
            if(id != null)
            {
                c = cd.GetById((int)id);
            }
            return View(c);
        }

        [HttpPost]
        public ActionResult Save(Post p, HttpPostedFileBase picture, int categoryId)
        {
            if (ModelState.IsValid)
            {
                if(picture != null)
                {
                    if(picture.ContentType == "image/jpeg" || picture.ContentType == "image/png")
                    {
                        Image image = Image.FromStream(picture.InputStream);
                        Bitmap small = new Bitmap(ImageUtils.ScaleImage(image, 350, 232));
                        Bitmap big =  new Bitmap(ImageUtils.ScaleImage(image, 1000, 664));

                        if(p.PreviewImageName != null)
                        {
                            System.IO.File.Delete(Server.MapPath("~/Upload/Small/" + p.PreviewImageName));
                        }
                        if(p.ContentImageName != null)
                        {
                            System.IO.File.Delete(Server.MapPath("~/Upload/" + p.ContentImageName));
                        }

                        p.PreviewImageName = saveImage(small, true);
                        p.ContentImageName = saveImage(big, false);

                        image.Dispose();
                        small.Dispose();
                        big.Dispose();
                    }
                    p.CreationDate = DateTime.Now;
                    CategoryDao cd = new CategoryDao();
                    Category c = cd.GetById(categoryId);
                    p.Category = c;

                    UserDao ud = new UserDao();
                    User u = ud.GetById(1);
                    p.Author = u;

                    PostDao pd = new PostDao();
                   if(p.Id != 0)
                    {
                        pd.Update(p);
                    }else
                    {
                        pd.Create(p);
                    }
                }
            }else
            {
                return View("Detail", p);
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult SaveCategory(Category c)
        {
            if (ModelState.IsValid)
            {
                CategoryDao cd = new CategoryDao();
                if (c.Id != 0)
                {
                    cd.Update(c);
                }
                else
                {
                    cd.Create(c);
                }
 
            }
            else
            {
                return View("DetailCategory", c);
            }
            return RedirectToAction("Index");
        }


        private string saveImage(Bitmap b, Boolean small)
        {
            if (small)
            {
                Guid guid = Guid.NewGuid();
                string imageName = guid.ToString() + "_small"+".jpg";
                b.Save(Server.MapPath("~/Upload/Small/" + imageName), ImageFormat.Jpeg);
                return imageName;
            }
            else
            {
                Guid guid = Guid.NewGuid();
                string imageName = guid.ToString() + ".jpg";
                b.Save(Server.MapPath("~/Upload/" + imageName), ImageFormat.Jpeg);
                return imageName;
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult DeletePost(int Id)
        {
            PostDao pd = new PostDao();
            Post p = pd.GetById(Id);

            System.IO.File.Delete(Server.MapPath("~/Upload/" + p.ContentImageName));
            System.IO.File.Delete(Server.MapPath("~/Upload/Small/" + p.PreviewImageName));

            CommentDao cd = new CommentDao();
            List<Comment> comments = cd.getAllForPost(Id);
            foreach(Comment c in comments)
            {
                cd.Delete(c);
            }

            pd.Delete(p);

            TempData["message-success"] = "Příspěvek " + p.Title + " byl úspěšně vymazán";
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "admin")]
        public ActionResult DeleteCategory(int Id)
        {
            CategoryDao cd = new CategoryDao();
            Category c = cd.GetById(Id);

            cd.Delete(c);

            TempData["message-success"] = "Kategorie " + c.Name + " byla úspěšně vymazána";
            return RedirectToAction("Index");
        }

    }
}

Blog/Controllers/MessageController.cs
using DataAccess.Dao;
using DataAccess.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class MessageController : Controller
    {
        // GET: Message
        public ActionResult Index()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }else
            {
                return View();
            }
           
        }

        public ActionResult Save(Message m)
        {
            if (ModelState.IsValid)
            {
                m.Completed = false;
                m.CreationDate = DateTime.Now;

                MessageDao md = new MessageDao();
                md.Create(m);

                return RedirectToAction("Index");
            }
            else
            {
                return View("Index", m);
            }
        }
    }
}

Blog/Views/Shared/_LayoutAdmin.cshtml
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="@Url.Content("~/Styles/blog.css")" rel="stylesheet" type="text/css" media="all" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" media="all" />
    <title>Problog Website Template | Single :: W3layouts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic+SC' rel='stylesheet' type='text/css'>

</head>
<body>
    <!-- Start-wrap -->
    <!-- Start-Header-->

    <div class="header">
        <div class="wrap">
            <!-- Start-logo-->
            <div class="logo">
                <a href="index.html"><img src="@Url.Content("~/Images/logo.png")" title="logo" /></a>
            </div>

            <!-- End-Logo-->
            <!-- Start-Header-nav-->

            <div class="clear"> </div>

            <!-- End-Header-nav-->
        </div>
    </div>
    <div class="header-nav1">
        <div class="wrap">
            <ul>
                <li class="current"><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li><a href="@Url.Action("Index", "Admin")">Admin</a></li>
                <li><a href="@Url.Action("Logout", "Login")">Login</a></li>
                <li><a href="#">Advertice</a></li>
                <li><a href="contact.html">Contact</a></li>
            </ul>

            <div class="search-bar">
                <ul>
                    <li><input type="text"></li>
                    <li><input type="submit" value="" /></li>
                </ul>
            </div>
        </div>

        <!-- End-Header-->
        <div class="clear"> </div>
        <!-- content-gallery-->
    </div>
    <div class="clear"> </div>
    <!-- End-content-gallery-->
    <!-- DC Pagination:C9 Start -->
    <div class="wrap">
        <div class="bloder-content">
            @RenderBody()
        </div>
        <div class="clear"> </div>

        <!-- DC Pagination:C9 End -->
    </div>
    <div class="clear"> </div>
    <div class="footer">
        <div class="wrap">
            <h3>SAY HELLO</h3>
            <p>
                Lorem ipsum dolor sit amet, consect etur adipiscing elit. Vestibulum ut tortor urnati dunt

                dolor. Nunc vulputate ultrices con sect etur donec semper lacinia ultri dolore cie

                lorem ipsum commete.
            </p>

            <div class="footerlinks">
                <div class="share">
                    <li><a href="#" target="_blank" title="Facebook"><span class="social fbook"> </span></a></li>
                    <li><a href="#" target="_blank" title="twitter"><span class="social twitter"> </span></a></li>
                    <li><a href="#" target="_blank" title="tumblr"><span class="social tumblr"> </span></a></li><br />
                    <li><a href="#" target="_blank" title="delicious"><span class="social delicious"> </span></a></li>
                    <li><a href="#" target="_blank" title="delicious"><span class="social delicious"> </span></a></li>
                    <li><a href="#" target="_blank" title="dribbble"><span class="social dribbble"> </span></a></li>
                    <li><a href="#" target="_blank" title="evernote"><span class="social evernote"> </span></a></li>
                    <li><a href="#" target="_blank" title="stumbleupon"><span class="social stumbleupon"> </span></a></li>
                </div>

            </div>
        </div>
    </div>
    <div class="footer1">
        <p class="link"><span>© All rights Reserved | Designed by&nbsp; <a href="http://w3layouts.com/"> W3Layouts</a>	</span></p>
    </div>
    <!-- End-wrap -->
    <script type="text/javascript" src="@Url.Content("~/scripts/bootstrap.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/scripts/tinymce/tinymce.min.js")"></script>
    <script>tinymce.init({ selector: '.formatedText' });</script>
</body>
</html>

Blog/Views/Shared/_LayoutDetail.cshtml
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="@Url.Content("~/Styles/blog.css")" rel="stylesheet" type="text/css" media="all" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/bootstrap-rating.css" rel="stylesheet" type="text/css" media="all" />
    <title>Problog Website Template | Single :: W3layouts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic+SC' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
    <link rel="stylesheet" href="~/Content/blueimp-gallery2/css/blueimp-gallery.min.css">
    <script type="text/javascript" src="~/scripts/jquery-1.10.2.min.js" ></script>
    <script type="text/javascript" src="@Url.Content("scripts/bootstrap.min.js")"></script>
    <script type="text/javascript" src="~/scripts/bootstrap-rating.min.js"></script>
</head>
<body>
    <!-- Start-wrap -->
    <!-- Start-Header-->
    <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
    <div id="blueimp-gallery" class="blueimp-gallery">
        <!-- The container for the modal slides -->
        <div class="slides"></div>
        <!-- Controls for the borderless lightbox -->
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
        <!-- The modal dialog, which will be used to wrap the lightbox content -->
        <div class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body next"></div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left prev">
                            <i class="glyphicon glyphicon-chevron-left"></i>
                            Previous
                        </button>
                        <button type="button" class="btn btn-primary next">
                            Next
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header">
        <div class="wrap">
            <!-- Start-logo-->
            <div class="logo">
                <a href="@Url.Action("Index", "Home")"><img src="@Url.Content("~/Images/logo.png")" title="logo" /></a>
            </div>

            <!-- End-Logo-->
            <!-- Start-Header-nav-->

            <div class="clear"> </div>

            <!-- End-Header-nav-->
        </div>
    </div>
    <div class="header-nav1">
        <div class="wrap">
            <ul>
                <li class="current"><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li>@Ajax.ActionLink("Uživatelelské články", "GetAjaxUsersPosts", "Home", new { detail = true }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "content" })</li>
                <li><a href="@Url.Action("Index", "Admin")">Admin</a></li>
                <li><a href="@Url.Action("Index", "Login", new { area = "Admin" })">Login</a></li>
                <li>@Ajax.ActionLink("Kontaktovat", "Index", "Message", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "content" })</li>
            </ul>

            <div class="search-bar">
                @using (Html.BeginForm("getAjaxContentByTitle", "Home", FormMethod.Post))
            {
                    <ul>
                        <li><input type="text" name="title"></li>
                        <li><input type="submit" value="" /></li>
                    </ul>
                }
            </div>
        </div>

        <!-- End-Header-->
        <div class="clear"> </div>
        <!-- content-gallery-->
    </div>
   
                  @RenderBody()
           
    <div class="clear"> </div>
    <!-- End-content-gallery-->
    <!-- DC Pagination:C9 Start -->
    <div class="wrap">

        <div class="clear"> </div>

        <!-- DC Pagination:C9 End -->
    </div>
    <div class="clear"> </div>
    <div class="footer">
        <div class="wrap">
            <h3>SAY HELLO</h3>
            <p>
                Lorem ipsum dolor sit amet, consect etur adipiscing elit. Vestibulum ut tortor urnati dunt

                dolor. Nunc vulputate ultrices con sect etur donec semper lacinia ultri dolore cie

                lorem ipsum commete.
            </p>

            <div class="footerlinks">
                <div class="share">
                    <li><a href="#" target="_blank" title="Facebook"><span class="social fbook"> </span></a></li>
                    <li><a href="#" target="_blank" title="twitter"><span class="social twitter"> </span></a></li>
                    <li><a href="#" target="_blank" title="tumblr"><span class="social tumblr"> </span></a></li><br />
                    <li><a href="#" target="_blank" title="delicious"><span class="social delicious"> </span></a></li>
                    <li><a href="#" target="_blank" title="delicious"><span class="social delicious"> </span></a></li>
                    <li><a href="#" target="_blank" title="dribbble"><span class="social dribbble"> </span></a></li>
                    <li><a href="#" target="_blank" title="evernote"><span class="social evernote"> </span></a></li>
                    <li><a href="#" target="_blank" title="stumbleupon"><span class="social stumbleupon"> </span></a></li>
                </div>

            </div>
        </div>
    </div>
    <div class="footer1">
        <p class="link"><span>© All rights Reserved | Designed by&nbsp; <a href="http://w3layouts.com/"> W3Layouts</a>	</span></p>
    </div>
    <!-- End-wrap -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
    <script src="~/Content/blueimp-gallery2/js/blueimp-gallery.min.js"></script>
</body>
</html>

Blog/Views/Shared/_LayoutMain.cshtml
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="@Url.Content("~/Styles/blog.css")" rel="stylesheet" type="text/css" media="all" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" media="all" />
    <title>Problog Website Template | Blog :: W3layouts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic+SC' rel='stylesheet' type='text/css'>
    <script src="@Url.Content("~/scripts/jquery-3.1.0.min.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.unobtrusive-ajax.min.js")"></script>
    <script src="@Url.Content("~/scripts/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script src="@Url.Content("~/scripts/MicrosoftAjax.js")"></script>
    <script src="@Url.Content("~/scripts/MicrosoftMvcAjax.js")"></script>
</head>
<body>
    <!-- Start-wrap -->
    <!-- Start-Header-->

    <div class="header">
        <div class="wrap">
            <!-- Start-logo-->
            <div class="logo">
                <a href="@Url.Action("Index", "Home")"><img src="@Url.Content("~/Images/logo.png")" title="logo" /></a>
            </div>

            <!-- End-Logo-->
            <!-- Start-Header-nav-->

            <div class="clear"> </div>

            <!-- End-Header-nav-->
        </div>
    </div>
    <div class="header-nav1">
        <div class="wrap">
            <ul>
                <li class="current"><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li>@Ajax.ActionLink("Uživateleské články", "GetAjaxUsersPosts", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "content" })</li>
                <li><a href="@Url.Action("Index", "Admin")">Admin</a></li>
                <li><a href="@Url.Action("Index", "Login", new { area = "Admin" })">Login</a></li>
                <li>@Ajax.ActionLink("Kontaktovat", "Index", "Message", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "content" })</li>
            </ul>

            <div class="search-bar">
            @using (Html.BeginForm("getAjaxContentByTitle", "Home", FormMethod.Post))
            {
                <ul>
                    <li><input type="text" name="title"></li>
                    <li><input type="submit" value="" /></li>
                </ul>
            }

            </div>
        </div>

        <!-- End-Header-->
        <div class="clear"> </div>
        <!-- content-gallery-->
    </div>
    <div id="content">
        @RenderBody()
    </div>
    <div class="footer">
        <div class="wrap">
            <h3>SAY HELLO</h3>
            <p>
                Lorem ipsum dolor sit amet, consect etur adipiscing elit. Vestibulum ut tortor urnati dunt

                dolor. Nunc vulputate ultrices con sect etur donec semper lacinia ultri dolore cie

                lorem ipsum commete.
            </p>

            <div class="footerlinks">
                <div class="share">
                    <li><a href="#" target="_blank" title="Facebook"><span class="social fbook"> </span></a></li>
                    <li><a href="#" target="_blank" title="twitter"><span class="social twitter"> </span></a></li>
                    <li><a href="#" target="_blank" title="tumblr"><span class="social tumblr"> </span></a></li><br />
                    <li><a href="#" target="_blank" title="delicious"><span class="social delicious"> </span></a></li>
                    <li><a href="#" target="_blank" title="delicious"><span class="social delicious"> </span></a></li>
                    <li><a href="#" target="_blank" title="dribbble"><span class="social dribbble"> </span></a></li>
                    <li><a href="#" target="_blank" title="evernote"><span class="social evernote"> </span></a></li>
                    <li><a href="#" target="_blank" title="stumbleupon"><span class="social stumbleupon"> </span></a></li>
                </div>

            </div>
        </div>
    </div>
    <div class="footer1">
        <p class="link"><span>© All rights Reserved | Designed by&nbsp; <a href="http://w3layouts.com/"> W3Layouts</a>	</span></p>
    </div>
    <!-- End-wrap -->


</body>
</html>