Blog/Controllers/ArticleController.cs
using System;
using DataAccess.Model;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Dao;
using Blog.Utils;

namespace Blog.Controllers
{
    public class ArticleController : Controller
    {
        // GET: Article
        public ActionResult Index(int id)
        {
            CategoryDao cd = new CategoryDao();
            setCategories();
            setArchives();
            setTags();
            ViewBag.Comments = findComments(id);
            ViewBag.Rating = getRating(id);
            return View(findPost(id));
        }

        public RatingViewModel getRating(int id)
        {
            PostDao pd = new PostDao();
            Post p = new Post();
            p = pd.GetById(id);

            int text = 0;
            int picture = 0;
            int edu = 0;
            int overall = 0;
            int celkem = 0;
            foreach(Rating ra in p.Ratings)
            {
                text = text + ra.TextQuality;
                picture = picture + ra.PictureQuality;
                edu = edu + ra.EducationalQuality;
                overall = overall + ra.OverallQuality;
                celkem = celkem++;
            }

            if(celkem != 0)
            {
                text = text / celkem;
                picture = picture /celkem;
                edu = edu / celkem;
                overall = overall / celkem;
            }

            RatingViewModel r = new RatingViewModel();
            r.TextQuality = text;
            r.PictureQuality = picture;
            r.EducationalQuality = edu;
            r.OverallQuality = overall;
            return r;
        }

        public ActionResult addComment(string Author, string Content, int Id)
        {
            if (ModelState.IsValid)
            {
                UserDao ud = new UserDao();
                User u = ud.GetByLogin(User.Identity.Name);
                PostDao pd = new PostDao();
                Post p = pd.GetById(Id);
                Comment c = new Comment() { Content = Content, Date = DateTime.Now, Article = p, User = u };
                CommentDao cd = new CommentDao();
                cd.Create(c);

                return RedirectToAction("Index", new { id = Id });
            }else
            {
                return View("Index", new { id = Id });
            }
          
        }

        public ActionResult addRating(int text, int picture, int edu, int overall, int Id)
        {
            RatingDao rd = new RatingDao();
            Rating r = new Rating();
            r.TextQuality = text;
            r.PictureQuality = picture;
            r.EducationalQuality = edu;
            r.OverallQuality = overall;

            UserDao ud = new UserDao();
            User u = ud.GetByLogin(User.Identity.Name);
            r.Author = u;

            PostDao pd = new PostDao();
            Post p = new Post();
            p = pd.GetById(Id);

            r.Article = p;

            rd.Create(r);

            return RedirectToAction("Index", new { id = Id });

        }

        private void setArchives()
        {
            PostDao pd = new PostDao();
            List<DateTime> dts = pd.getAllDates();
            ViewBag.Dates = DateUtils.getMonthNames(dts[0], dts[dts.Count - 1]);
        }

        private void setCategories()
        {
            CategoryDao cd = new CategoryDao();
            ViewBag.Categories = cd.GetAll();
        }

        private Post findPost(int id)
        {
            PostDao pd = new PostDao();
            Post p = pd.GetById(id);
            return p;
        }
        
        private List<Comment> findComments(int id)
        {
            CommentDao cd = new CommentDao();

            return cd.getAllForPost(id);
        }
        private void setTags()
        {
            TagDao td = new TagDao();
            ViewBag.Tags = td.findAllActive();
        }
    }
}

Blog/Views/Article/Index.cshtml
@using DataAccess.Model
@model Post
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDetail.cshtml";
}

<div class="wrap" id="wrap">
    <div class="about">
        <div class="services-sidebar">
            <h4>Categories</h4>
            @foreach (Category c in ViewBag.Categories)
            {
                <ul>
                    <li><img src="@Url.Content("~/Images/pointer.png")" title="pointer" />@Ajax.ActionLink(c.Name, "GetAjaxContent", "Home", new { id = @c.Id, detail = true }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "content" })</li>
                </ul>
            }
            <h4>Archives</h4>
            @foreach (DateTime dt in ViewBag.Dates)
            {
                <ul>
                    <li><img src="@Url.Content("~/Images/pointer.png")" title="pointer" />@Ajax.ActionLink(@dt.Month + " - " + @dt.Year, "GetAjaxContentByDate", "Home", new { date = @dt, detail = true }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "content" })</li>
                </ul>
            }
            <h4>Tags</h4>
            @foreach (Tag t in ViewBag.Tags)
            {
                <ul>
                    <li><img src="@Url.Content("~/Images/pointer.png")" title="pointer" />@Ajax.ActionLink(@t.Name != "" ? @t.Name : "Default", "GetAjaxPostByTag", "Home", new { idTag = @t.Id, detail = true }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "content" })</li>
                </ul>
            }


        </div>
        <div class="blog-box1">
            <div class="blog-box-image">
                <img src="@Url.Content("~/Upload/" + Model.ContentImageName)" title="priview" />
            </div>
            <div class="blog-box-content">
                <h5><a href="#">@Model.Title</a></h5>
                <p>
                    @Html.Raw(Model.Content)
                </p>
                <p>
                    <h3>Fotogalerie</h3>
                    @foreach (BlogImage bi in Model.Gallery)
                    {
                        <div id="links" style="float:left">
                            <a href="@Url.Content("~/Upload/Gallery/"+bi.Name+bi.Postfix)" data-gallery>
                                <img src="@Url.Content("~/Upload/Gallery/Small/"+bi.Name+"small"+bi.Postfix)" alt="Banana">
                            </a>
                        </div>
                    }
                </p>
                <p>
                    <div class="clearfix"></div>
                    <br/>
                    <h3>Hodnocení článku</h3>
                   
                    <table>
                        <tr><th>Kvalita textu: </th><td><input type="hidden" class="rating" data-readonly value="@ViewBag.Rating.TextQuality" /></td></tr>
                        <tr><th>Kvalita obrázků: </th><td><input type="hidden" class="rating" data-readonly value="@ViewBag.Rating.PictureQuality" /></td></tr>
                        <tr><th>Kvalita informací: </th><td><input type="hidden" class="rating" data-readonly value="@ViewBag.Rating.EducationalQuality" /></td></tr>
                        <tr><th>Celkový dojem: </th><td><input type="hidden" class="rating" data-readonly value="@ViewBag.Rating.OverallQuality" /></td></tr>
                    </table> 
                    
                    <hr />
                    <ul>
                        <li><a href="#">@Model.Author.Name @Model.Author.Surname - @Model.CreationDate</a></li>
                    </ul>
                </p>
            </div>
            <div class="clearfix"></div>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="row">
                    <div class="col-sm-5">
                        @using (Html.BeginForm("addComment", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
                        {
                            <input type="hidden" name="Id" value="@Model.Id" />

                            <div class="form-group">
                                <label for="inputText">Text komentáře</label>
                                <textarea class="form-control" name="Content" rows="5"></textarea>
                            </div>
                            <button type="submit" class="btn btn-default">Submit</button>
                        }
                    </div>
                    <div class="col-sm-2">
                    </div>
                    <div class="col-sm-5">
                        @using (Html.BeginForm("addRating", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
                        {
                            <input type="hidden" name="Id" value="@Model.Id" />
                            <div class="form-group">
                                <label for="inputText">Kvalita textu:</label>
                                <input type="hidden" name="text" class="rating" />
                            </div>
                            <div class="form-group">
                                <label for="inputText">Kvalita obrázků:</label>
                                <input type="hidden" name="picture" class="rating" />
                            </div>
                            <div class="form-group">
                                <label for="inputText">Kvalita informací:</label>
                                <input type="hidden" name="edu" class="rating" />
                            </div>
                            <div class="form-group">
                                <label for="inputText">Celkový dojem:</label>
                                <input type="hidden" name="overall" class="rating" />
                            </div>
                            <button type="submit" class="btn btn-default">Submit</button>
                        }
                    </div>
                </div>
            }
           
           
           
            <br/>
            @if (ViewBag.Comments.Count == 0)
            {
                <p> Zatím nebyly vloženy žádné komenáře.</p>
            }
            else
            {
                foreach (Comment c in ViewBag.Comments)
                {
                    <hr />
                    <p>
                        @c.User.Name @c.User.Surname -  @c.Date
                    </p>
                        <p>
                            @c.Content
                        </p>
                        <hr />
                }
            }
           
        </div>
        <div class="clear"> </div>

    </div>
</div>